name: Zero-Downtime Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  package-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Get timestamp
        id: vars
        run: echo "sha_short=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Zip files
        run: zip -r Full-Library-${{ env.sha_short }}.zip . -x "*.git*" -x "*.github*"

      - name: Create New Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.sha_short }}
          name: Archive Update ${{ env.sha_short }}
          files: Full-Library-${{ env.sha_short }}.zip
          body: "גרסה אוטומטית מעודכנת."
          make_latest: true # זה הופך את זה לגרסה הרשמית החדשה רק כשהכל מוכן
